### ISSUE TITLE
Flux timeout marked as failure by ATS

### ISSUE THREAD

**Issue by MishaZakharchanka** [LLNL/ATS#116]
When a in Flux times out after being started with the "-t" option ATS marks it as a failure. Flux throws a job.exception that has a type of timeout, this information could be used in ATS to properly report timeouts.

Here is the output of a test that have timed out and currently reports FAIL:
5.035s: job.exception type=timeout severity=0 resource allocation expired
flux-job: task(s) exited with exit code 142

**Comment by dawson6** [comment]
Misha, do you think it would be possible to update the flux module to put the timeout tests into the TIMEOUT category rather than the FAILEd?
