### ISSUE TITLE
Update Warnings/Errors to have consistent prefixes

### ISSUE THREAD

**Issue by white238** [LLNL/ATS#21]
Having a consistent prefix for logging messages across ATS is helpful when searching logs.  Something like:

"ERROR: <message>"
"WARNING: <message>"

**Comment by MishaZakharchanka** [comment]
@dawson6 Do we want to have "ATS" as a prefix to our printed and logged statements? Is it a common problem to have many error or warning messages that are mixed from different codes and it isn't clear who/what is causing the issue?

**Comment by dawson6** [comment]
I think standardizing on ATS as the prefix for messages sounds fine.

**Comment by dawson6** [comment]
@MishaZakharchanka  has addressed this with a MR.
