### ISSUE TITLE
ATS does not return error codes on failed tests

### ISSUE THREAD

**Issue by white238** [LLNL/ATS#90]
This function says that it returns false on interrupted or failed tests but there isn't a return statement:

https://github.com/LLNL/ATS/blob/7ed78d69f087cae67ac78e4fd94b483b98c18a70/ats/management.py#L661-L683

This causes problems in CI because unless you parse the reports for failed tests, jobs do not mark themselves as failures.

**Comment by dawson6** [comment]
Well, that is odd.  Nobody has mentioned this before.  But it should be fixable for sure.

**Comment by davidbloss** [comment]
@white238 I am talking with @dawson6 about this now and I am going to take a more thorough look at this. At a glance it seems like something that has been there but not addressed for.... years.

**Comment by MishaZakharchanka** [comment]
@white238 I'm working on this issue now and so far I have main() returning false on: keyboard interrupts, ATS errors, and failed tests. Would you want/expect main() to return false on tests that have timed out and/or halted as well? Or in a more general sense, would you expect main to return false for anything but all tests running successfully?

**Comment by white238** [comment]
Yes, I would expect it to return false for anything but the tests running successfully.

**Comment by MishaZakharchanka** [comment]
@white238 I believe that I have added the missing functionality and tests are passing on our side. Is there any specific way that you would like to test this? I can make a public install for you or you can try with either the the branch linked to this issue or once the changes are pushed to the main branch.

**Comment by white238** [comment]
Thanks for looking into this. I will try to try this out soon but I am fine with you guys closing this and leaving it up to me to test.
